export const projects = [
  {
    name: "Freelance Homepage",
    githubUrl: "",
    image: "/assets/projects/1.png",
    category: ["react", "aws"],
  },
  {
    name: "Work Style Media",
    githubUrl: "",
    image: "/assets/projects/2.png",
    category: ["react", "aws"],
  },
  {
    name: "Marketing Strategy",
    githubUrl: "",
    image: "/assets/projects/3.png",
    category: ["react", "aws"],
  },
  {
    name: "Student Media",
    githubUrl: "",
    image: "/assets/projects/4.png",
    category: ["react"],
    projextUrl: "",
    deployed: true,
  },
  {
    name: "Business Branding Page",
    githubUrl: "",
    image: "/assets/projects/5.png",
    category: ["react"],
  },
  {
    name: "Portfolio",
    githubUrl: "",
    image: "/assets/projects/6.png",
    category: ["wordpress"],
    projextUrl: "",
    deployed: true,
  },
  {
    name: "Cosmetics Media",
    githubUrl: "",
    image: "/assets/projects/7.png",
    category: ["react"],
    projextUrl: "",
    deployed: true,
  },
  {
    name: "Blog Media",
    githubUrl: "",
    image: "/assets/projects/8.png",
    category: ["react"],
    projextUrl: "",
    deployed: true,
  },
  {
    name: "Product Introduction",
    githubUrl: "",
    image: "/assets/projects/9.png",
    category: ["wordpress"],
  },
  {
    name: "Company Website",
    githubUrl: "",
    image: "/assets/projects/10.png",
    category: ["react"],
    projextUrl: "",
    deployed: true,
  },
  {
    name: "Online Distribution Page",
    githubUrl: "",
    image: "/assets/projects/11.png",
    category: ["wordpress"],
  },
  {
    name: "Event Page",
    githubUrl: "",
    image: "/assets/projects/12.png",
    category: ["react"],
  },
];
